# Generated by Django 6.0.2 on 2026-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_one', models.CharField(max_length=200)),
                ('feature_two', models.TextField()),
                ('feature_three', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
